<?xml version="1.0" ?>
<robot name="amp_kart" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:include filename="$(find amp_kart_description)/urdf/macros.xacro" />

  <!-- Kart Dimmensions-->

  <xacro:property name="chassis_width" value="1.42" />
  <xacro:property name="chassis_length" value="1.94" />
  <xacro:property name="chassis_height" value="0.5" />
  <xacro:property name="chassis_xoff" value="-0.60" />
  <xacro:property name="chassis_zoff" value="0.171" />
  <xacro:property name="chassis_mass" value="40" />

  <xacro:property name="fwheel_radius" value="0.13" />
  <xacro:property name="fwheel_width" value="0.13" />
  <xacro:property name="fwheel_yoff" value="0.71" />
  <xacro:property name="fwheel_mass" value="0.4" />

  <xacro:property name="wheelbase" value="1.05" />
  <xacro:property name="rwheel_radius" value="0.14" />
  <xacro:property name="rwheel_width" value="0.21" />
  <xacro:property name="rwheel_yoff" value="0.71" />
  <xacro:property name="rwheel_zoff" value="${rwheel_radius-fwheel_radius}" />
  <xacro:property name="rwheel_mass" value="0.5" />



  <!-- Necessary Dimensions -->

  <xacro:property name="chassisInertia_xoff" value="0" />
  <xacro:property name="chassisInertia_yoff" value="0" />
  <xacro:property name="chassisInertia_zoff" value="0" />

  <xacro:property name="baseLink_xoff" value="0" />
  <xacro:property name="baseLink_yoff" value="0" />
  <xacro:property name="baseLink_zoff" value="0.05" />

  <xacro:property name="lRear_xoff" value="0" />
  <xacro:property name="lRear_yoff" value="0.1" />
  <xacro:property name="lRear_zoff" value="0" />

  <xacro:property name="rRear_xoff" value="0" />
  <xacro:property name="rRear_yoff" value="-0.1" />
  <xacro:property name="rRear_zoff" value="0" />

  <xacro:property name="lSteerHinge_xoff" value="0.325" />
  <xacro:property name="lSteerHinge_yoff" value="0.1" />
  <xacro:property name="lSteerHinge_zoff" value="0" />

  <xacro:property name="rSteerHinge_xoff" value="0.325" />
  <xacro:property name="rSteerHinge_yoff" value="-0.1" />
  <xacro:property name="rSteerHinge_zoff" value="0" />

  <xacro:property name="lfront_xoff" value="0" />
  <xacro:property name="lfront_yoff" value="0" />
  <xacro:property name="lfront_zoff" value="0" />

  <xacro:property name="rfront_xoff" value="0" />
  <xacro:property name="rfront_yoff" value="0" />
  <xacro:property name="rfront_zoff" value="0" />

  <xacro:property name="lidar_xoff" value="1.2192" />
  <xacro:property name="lidar_zoff" value="0.508" />

  <!-- Add chassis and it's inertia link -->

  <link name="base_link" />

  <link name="chassis">
    <visual>
      <xacro:chassis_geometry />
      <material name="blue" />
    </visual>
    <collision>
    	<xacro:chassis_geometry />
    </collision>
  </link>

  <joint name="base_link_joint" type="fixed">
    <origin
      xyz="${baseLink_xoff} ${baseLink_yoff} ${baseLink_zoff}"
      rpy="0 0 0"
    />
    <parent link="base_link" />
    <child link="chassis" />
  </joint>

  <link name="chassis_inertia">
    <inertial>
      <xacro:chassis_inertial_params />
    </inertial>
  </link>

  <joint name="chassis_inertia_joint" type="fixed">
    <origin
      xyz="${chassisInertia_xoff} ${chassisInertia_yoff} ${chassisInertia_zoff}"
      rpy="0 0 0"
    />
    <parent link="chassis" />
    <child link="chassis_inertia" />
  </joint>

  <!-- Add the left rear wheel with its joints and tranmissions -->

  <link name="left_rear_wheel">
    <inertial>
      <xacro:left_wheels_inertial_params />
    </inertial>
    <visual>
      <xacro:left_rear_wheel_geometry />
      <material name="black" />
    </visual>
    <collision>
      <xacro:left_wheels_collision_geometry />
    </collision>
  </link>

  <joint name="left_rear_wheel_joint" type="continuous">
    <origin xyz="${lRear_xoff} ${lRear_yoff} ${lRear_zoff}" rpy="1.5708 0 0" />
    <parent link="chassis" />
    <child link="left_rear_wheel" />
    <axis xyz="0 0 -1" />
    <limit effort="10" velocity="100" />
  </joint>

  <xacro:wheel_transmission name="left_rear_wheel" />

  <!-- Add the right rear wheel with its joints and tranmissions -->

  <link name="right_rear_wheel">
    <inertial>
      <xacro:right_wheels_inertial_params />
    </inertial>
    <visual>
      <xacro:right_rear_wheel_geometry />
      <material name="black" />
    </visual>
    <collision>
      <xacro:right_wheels_collision_geometry />
    </collision>
  </link>

  <joint name="right_rear_wheel_joint" type="continuous">
    <origin xyz="${rRear_xoff} ${rRear_yoff} ${rRear_zoff}" rpy="1.5708 0 0" />
    <parent link="chassis" />
    <child link="right_rear_wheel" />
    <axis xyz="0 0 -1" />
    <limit effort="10" velocity="100" />
  </joint>

  <xacro:wheel_transmission name="right_rear_wheel" />

  <!-- Add the left steering hinge with its joints and tranmissions -->

  <link name="left_steering_hinge">
    <inertial>
      <xacro:steering_hinge_inertial_params />
    </inertial>
    <visual>
      <xacro:left_steering_hinge_geometry />
      <material name="grey" />
    </visual>
  </link>

  <joint name="left_steering_hinge_joint" type="revolute">
    <origin
      xyz="${lSteerHinge_xoff} ${lSteerHinge_yoff} ${lSteerHinge_zoff}"
      rpy="0 1.5708 0"
    />
    <parent link="chassis" />
    <child link="left_steering_hinge" />
    <axis xyz="-1 0 0" />
    <limit lower="-1" upper="1" effort="10" velocity="100" />
  </joint>

  <xacro:steering_hinge_transmission name="left_steering_hinge" />

  <!-- Add the right steering hinge with its joints and tranmissions -->

  <link name="right_steering_hinge">
    <inertial>
      <xacro:steering_hinge_inertial_params />
    </inertial>
    <visual>
      <xacro:right_steering_hinge_geometry />
      <material name="grey" />
    </visual>
  </link>

  <joint name="right_steering_hinge_joint" type="continuous">
    <origin
      xyz="${rSteerHinge_xoff} ${rSteerHinge_yoff} ${rSteerHinge_zoff}"
      rpy="0 1.5708 0"
    />
    <parent link="chassis" />
    <child link="right_steering_hinge" />
    <axis xyz="-1 0 0" />
    <limit lower="-1" upper="1" effort="10" velocity="100" />
  </joint>

  <xacro:steering_hinge_transmission name="right_steering_hinge" />

  <!-- Add the left front wheel with its joints and tranmissions -->

  <link name="left_front_wheel">
    <inertial>
      <xacro:left_wheels_inertial_params />
    </inertial>
    <visual>
      <xacro:left_front_wheel_geometry />
      <material name="black" />
    </visual>
    <collision>
      <xacro:left_wheels_collision_geometry />
    </collision>
  </link>

  <joint name="left_front_wheel_joint" type="continuous">
    <origin
      xyz="${lfront_xoff} ${lfront_yoff} ${lfront_zoff}"
      rpy="1.5708 0 0"
    />
    <parent link="left_steering_hinge" />
    <child link="left_front_wheel" />
    <axis xyz="0 0 -1" />
    <limit effort="10" velocity="100" />
  </joint>

  <xacro:wheel_transmission name="left_front_wheel" />

  <!-- Add the left front wheel with its joints and tranmissions -->

  <link name="right_front_wheel">
    <inertial>
      <xacro:right_wheels_inertial_params />
    </inertial>
    <visual>
      <xacro:right_front_wheel_geometry />
      <material name="black" />
    </visual>
    <collision>
      <xacro:right_wheels_collision_geometry />
    </collision>
  </link>

  <joint name="right_front_wheel_joint" type="continuous">
    <origin
      xyz="${rfront_xoff} ${rfront_yoff} ${rfront_zoff}"
      rpy="1.5708 0 0"
    />
    <parent link="right_steering_hinge" />
    <child link="right_front_wheel" />
    <axis xyz="0 0 -1" />
    <limit effort="10" velocity="100" />
  </joint>

  <xacro:wheel_transmission name="right_front_wheel" />

  <!-- VLP-16 -->
  <xacro:include
    filename="$(find velodyne_description)/urdf/VLP-16.urdf.xacro"
  />
  <xacro:VLP-16
    parent="base_link"
    name="velodyne"
    topic="/velodyne_points"
    hz="10"
    samples="440"
    gpu="false"
  >
  <origin xyz="${lidar_xoff} 0 ${lidar_zoff}" rpy="0 0 0" />
  </xacro:VLP-16>

  <!-- Add the remaining xacros -->
  <xacro:include filename="$(find amp_kart_description)/urdf/racecar.gazebo" />
  <xacro:include filename="$(find amp_kart_description)/urdf/materials.xacro" />

</robot>
