costmap/costmap_node:
    ros__parameters:
      static_map: false
      rolling_window: true
      always_send_full_costmap: False

      footprint_padding: 0.05
      footprint: "[[-0.3556, 0.7112], [-0.3556, -0.7112], [1.6256, -0.7112], [1.6256, 0.7112]]"
      
      global_frame: base_link
      robot_base_frame: base_link

      height: 10
      width: 10
      lethal_cost_threshold: 100

      publish_frequency: 2.0
      resolution: 0.05
      
      track_unknown_space: false
      transform_tolerance: 0.3
      update_frequency: 5.0

      use_maximum: False
      use_sim_time: False

      plugins: ["obstacle_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayers"
        cost_scaling_factor: 1.0
        inflation_radius: 0.55
        observation_sources: pointcloud
        combination_method: 1
        pointcloud:  # no frame set, uses frame from message
          topic: /nonground
          max_obstacle_height: 2.0
          min_obstacle_height: 0.0
          obstacle_max_range: 20
          obstacle_min_range: 0.0

          clearing: True
          raytrace_max_range: 2.0
          raytrace_min_range: 0.0
          
          marking: True
          data_type: "PointCloud2"
