twist_mux:
  ros__parameters:
    locks:
      joy_disable:
        topic: joy_disable
        timeout: 0.0
        priority: 150
    topics:
      joy_vel:
        topic: joy_vel
        timeout: 0.5
        priority: 100
