amp_local_goal:
  ros__parameters:
    goal_update_freq: 3 # Frequency to publish goal pose regardless of costmap availability
    parabola_numer: -4 # Goal selection is fixed to a prabolic region in order to bias it to the robot's "front"
    parabola_denomi: 5
    show_costmaps: false # Debugging views
    costmap_threshold: 100 # Threshold above which costmap voxels are treated as obstacles
